apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: springboot-cluster
  region: us-east-1
availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]
managedNodeGroups:
  - name: ng-1
    instanceType: t3a.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 8